#!/usr/bin/env python3
"""Generate Panta market specs for a GW6 target list.

Two things this encodes that are easy to get wrong by hand:

  endTime = KICKOFF, not kickoff + 2h.

    Panta's market page says of endTime: "All trading stops here". Set it to
    full time and traders can watch the player score and then buy YES. That is
    a fairness hole, not a feature. The first market we created has it wrong and
    cannot now be changed; every one after this uses kickoff.

  startTime is ISO 8601 in the spec file and converted to unix seconds on the
  wire by create-market.ts, because the API takes seconds and humans edit files.

    python scripts/make_market_specs.py
"""

from __future__ import annotations

import datetime as dt
import json
import urllib.request
from pathlib import Path

UA = "Overline/0.1 (+https://github.com/yeziR4/fpl)"
BOOTSTRAP = "https://fantasy.premierleague.com/api/bootstrap-static/"
OUT = Path(__file__).resolve().parent.parent / "panta-signer" / "examples"

# (slug, display name, FPL web_name to match, line, position, kickoff UTC, fixture)
#
# Two marquee forwards rather than one-per-position. The earlier set was chosen
# for statistical diversity -- FWD/MID/DEF, three different fixtures -- but two
# of the game's most-owned forwards make a better public market set for a
# product nobody has heard of yet. Reach beats spread here. Saka (14.2% owned)
# was the weakest of the four on audience and is already live anyway.
TARGETS = [
    ("joaopedro",  "João Pedro",      "Pedro",      8, "FWD", "2026-10-10T14:00:00Z", "Chelsea v Bournemouth"),
    ("haaland",    "Erling Haaland",  "Haaland",    8, "FWD", "2026-10-11T15:30:00Z", "Liverpool v Manchester City"),
]

PHOTO = "https://resources.premierleague.com/premierleague/photos/players/250x250/p%d.png"
RESOLUTION_TIME = "2026-10-12T12:00:00Z"


def get(url):
    req = urllib.request.Request(url)
    req.add_header("User-Agent", UA)
    with urllib.request.urlopen(req, timeout=45) as resp:
        return json.loads(resp.read().decode())


boot = get(BOOTSTRAP)
elements = boot["elements"]
gw = next(e["id"] for e in boot["events"] if e.get("is_next"))

specs = []
for slug, display, match, line, pos, kickoff, fixture in TARGETS:
    hits = [e for e in elements if match.lower() in (e.get("web_name") or "").lower()]
    hits.sort(key=lambda e: -float(e.get("selected_by_percent") or 0))
    if not hits:
        print("!! no player matched %r -- skipped" % match)
        continue
    p = hits[0]
    code = p["code"]
    real_name = p["web_name"]
    ownership = float(p.get("selected_by_percent") or 0)

    spec = {
        "_comment": "Generated by scripts/make_market_specs.py. Field names verified against the Panta API reference.",
        "_timing": "endTime is KICKOFF: Panta stops trading at endTime, so anything later lets traders act on in-play information.",
        "_line": "Calibrated per position: FWD 8+ / MID 7+ / DEF 5+ all land in Panta's full 20%% creator-royalty band. A 10+ forward line clears only 7.2%% of the time and drops it to 5%%.",
        "_pool": "Top 10-20 by ownership, price or season points -- not every player in the gameweek.",
        "_verified": "ownership %s%%" % ownership,
        # `display` is the full name as a person writes it, accents included;
        # `real_name` is FPL's short web_name ("Haaland"), which reads as
        # informal in a market question. Title takes the short one, the prose
        # that a stranger will read on a public market page takes the full one.
        "title": "%s %d+ points, GW%d" % (real_name, line, gw),
        "question": "Will %s score %d or more Fantasy Premier League points in Gameweek %d (%s)?" % (display, line, gw, fixture),
        "resolutionRule": (
            "Resolves YES if the official Fantasy Premier League site credits %s with %d or more "
            "points for Gameweek %d, once every match in that gameweek is marked finished and bonus "
            "points are final. Resolves NO otherwise." % (display, line, gw)
        ),
        "sourcesOfTruth": [
            "https://fantasy.premierleague.com/api/bootstrap-static/",
            "https://fantasy.premierleague.com/api/event/%d/live/" % gw,
        ],
        "category": "sports",
        "region": "Global",
        "startTime": kickoff,
        "endTime": kickoff,
        "resolutionTime": RESOLUTION_TIME,
        "marketType": "breaking",
        "imageUrl": PHOTO % code,
        "_position": pos,
        "_note_duplicate": "Panta keys an active create session on wallet + question. Dry-run with a THROWAWAY keypair so the operator wallet keeps no session open.",
    }
    path = OUT / ("market-spec.%s.json" % slug)
    path.write_text(json.dumps(spec, indent=2, ensure_ascii=True) + "\n", encoding="ascii")
    specs.append((slug, real_name, line, pos, kickoff, ownership, code))
    print("wrote %-34s %-16s %s %d+  %s  (owned %.1f%%)" % (path.name, real_name, pos, line, kickoff, ownership))

print()
print("startTime == endTime for every market: trading stops at kickoff.")
